### ISSUE TITLE
ошибки (лабораторная 1)

### ISSUE THREAD

**Issue by solovevayaroslavna** [artwh/artemBelozertsev_6132#2]
![image](https://user-images.githubusercontent.com/90199600/201520061-e8306a46-3728-465e-bdb3-f86125e8f75e.png)

выглядит неверно

task1 влита не в main a в task 4

рисунок веток должен выглядеть так - 
![image](https://user-images.githubusercontent.com/90199600/201520158-99ba2caf-1cfa-4fd5-abae-57fe01f32501.png)

**Comment by artwh** [comment]
Добрый день! Возможно где-то нарушилась последовательность, но коммиты и их кол-во соответствует веткам
